name = "mirackle-support"
main = "src/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "mirackle-support-media"

[[d1_databases]]
binding = "DB"
database_name = "mirackle-tickets"
database_id = "PEGA_AQUI_TU_DATABASE_ID"

[vars]
MAIL_TO = "contact@mirackle.us"
MAIL_FROM_EMAIL = "contact@mirackle.us"
MAIL_FROM_NAME = "Mirackle Support"
