name = "mirackle-support"
main = "src/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "mirackle-support-media"

[[d1_databases]]
binding = "DB"
database_name = "mirackle-tickets"
database_id = "7ad0dc7e-c09d-4c5b-9166-3d1fa7f8b882"

[vars]
MAIL_TO = "contact@mirackle.us"
MAIL_FROM_EMAIL = "marlonlamilla7@gmail.com"
MAIL_FROM_NAME = "Mirackle Support"

[[unsafe.bindings]]
